baseURL = "https://jonbooz.github.io/"
languageCode = "en-us"
title = "Jon Booz"
theme = "PaperMod"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
description = "Jon Booz - Meditations on Life"
author = "Jon Booz"

[params.homeInfoParams]
Title = "Jon Booz"
