baseURL = "http://jonbooz-com-dev.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-us"
title = "Jon Booz (dev)"
theme = "PaperMod"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "dev"
description = "Jon Booz - Meditations on Life"
author = "Jon Booz"

[params.homeInfoParams]
Title = "Jon Booz"

[deployment]
order = [ ".jpg$", ".gif$" ]

[[deployment.targets]]
name = "s3-dev"
URL = "s3://jonbooz-com-dev?region=us-east-1"
