baseURL: 'https://jonbooz.github.io/'
languageCode: 'en-us'
title: 'Jon Booz'
theme: "PaperMod"

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Jon Booz - Meditations on Life"
  author: Jon Booz

  homeInfoParams:
    Title: "Jon Booz"
    Content: >
      Jon Booz's Meditations on Life
