buildDrafts = "true"
baseURL = "http://jonbooz-com-dev.s3-website-us-east-1.amazonaws.com"

[params]
env = "development"

[deployment]
order = [ ".jpg$", ".gif$" ]

[[deployment.targets]]
name = "s3-dev"
URL = "s3://jonbooz-com-dev?region=us-east-1"
